### ISSUE TITLE
Write Golang tests for repositories and other files

### ISSUE THREAD

**Issue by rodrigo-brito** [rodrigo-brito/bus-api-go#2]
The bus repository has a test example. Other files can be tested too. [Repository example](https://github.com/rodrigo-brito/bus-api-go/blob/master/domain/bus/repository/repository_test.go)

You don't need write all tests, **only one test will help a lot.**

Please use the BDD method for the tests.

**Comment by ibtehalahmed** [comment]
Can i help with this @rodrigo-brito ?

**Comment by rodrigo-brito** [comment]
Yes! Have fun @ibtehalahmed
