### ISSUE TITLE
Fix Travis coverage script

### ISSUE THREAD

**Issue by rodrigo-brito** [rodrigo-brito/bus-api-go#3]
Actually, the coverage script is showing a wrong coverage percentage. Only one file has 86% of coverage, the other files was ignored in the metric.

**Comment by calvn** [comment]
I think I can help out with this one.

**Comment by rodrigo-brito** [comment]
Thank you @calvn, maybe changing the `go test` script solve it. See it: https://github.com/modocache/gover

**Comment by calvn** [comment]
Unfortunately changing the script won’t solve it, as gover uses the cover profiles from the packages, but those will not be generated if there are no test files present.

**Comment by rodrigo-brito** [comment]
Closed by https://github.com/rodrigo-brito/bus-api-go/pull/4
